### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by cjackie**

### CODE REVIEW

**Comment by kbumsik** [comment]
Flux?

**Comment by cjackie** [comment]
yea. If you google "flux reactjs", you will see.

Facebook uses this architecture for doing their user interface.

My code is getting messy. I think I need to separate different modules into files. Maybe use Requirejs. But there is learning curve, and I'm not satisfied how it will integrate with ReactJS and Flux.

**Comment by kbumsik** [comment]
I see. Looks like the world of front-end frameworks is totally different from others, because of JS.

**Comment by cjackie** [comment]
Yes. Very messy because of JS... lol

**Pull request merged**
