### PR TITLE
Support /api/device API and change in DB layers

### PR DESCRIPTION
**Pull request by kbumsik**
Because there are numerous changes in Back-end so I would make PR rather than just push in `master` branch.

Since there are changes in DB schema, please delete `wolfie_home.db` and then run `db_clean_tables.py` and `db_create_default_data.py` after applying changes
# Changes
1. Added support following Web APIs (all tested):
   - `GET /api/location/<id>`
   - `GET /api/location/<id>/device`
   - `GET /api/device`
   - `GET /api/device/<id>`
   - `GET /api/device/<id>/parameter`
2. Added `DAO` layer
   - Added because `Device` service becomes complicated so I need to separate `service` and `dao`
   - It is a collection of most basic SQL operation methods.
   - Each methods should be one of CRUD (Create, Read, Update, Delete) operation.
   - Now `service` layer (except User create/login) call `DAO` method most of time, instead of calling SQL statements directly 
3. Dropped `Models` class methods (instead, new we use `Service` methods
   - `Models` only represents how the data look like, so they should not have model creation/get methods.
   - Now program calls `Service` method to create `Model` instances. You can think `Service` classes are kinds of Factory class pattern.
4. Changed columns name of table in DB.
   - For conformance to python coding convention.
   - The advantage is that we now can match `Models` attributes using python's keyword arguments conveniently.
# Issues
- `controllable` field in `Parameters` have 0/1 values, not False/True
- Most APIs returns unnecessary extra fields. They still meet `Design Document` very well but you will see APIs sending extra information. Pleas do not use these extras, just follow `Design Document`.
- APIs relating to `Device` will return Null values for `time` and `value`. Value insertion is not implemented yet.
- `Device`'s `class_id` always has Null value too. They are not implemented neither.
# 

Please merge it if you see changes.

whoa, Now I can focus on my homeworks this week 😝

### CODE REVIEW

**Comment by cjackie** [comment]
I ran "python3 runserver", and got errors.

**Comment by kbumsik** [comment]
Can I get any error message?

**Comment by cjackie** [comment]
Never mind, I know why. DB schema has changed. I need to run `db_clean_tables.py` and `db_create_default_data.py` first.

Nice job!!! I'm not sure I can keep up with your pace. 😆  I will code a little bit tonight.

> whoa, Now I can focus on my homeworks this week

haha, yea. focus on your homework first.

**Comment by kbumsik** [comment]
Don't worry. Cuz I have a lots of things behind..like hardware lol

**Comment by cjackie** [comment]
Haha. Forget about hardware for now. If we could finished this website by the end of semester, we will be awesome!!!

**Pull request merged**
